companies:
  MFC:
    name: Manuvie
    fullName: La Société Financière Manuvie
    ticker: MFC.TO
    investorRelationsUrl: https://www.manulife.com/ca/en/about-us/investors/results-and-reports
  SLF:
    name: Sun Life
    fullName: Sun Life Financial Inc.
    ticker: SLF.TO
    investorRelationsUrl: https://www.sunlife.com/en/investors/financial-results-and-reports/quarterly-reports/
  GWO:
    name: Great-West Lifeco
    fullName: Great-West Lifeco Inc.
    ticker: GWO.TO
    investorRelationsUrl: https://www.greatwestlifeco.com/news-events/annual-reports.html
  IAG:
    name: iA Groupe financier
    fullName: iA Société financière inc.
    ticker: IAG.TO
    investorRelationsUrl: https://ia.ca/a-propos/investisseurs/rapports-financiers
